INSERT INTO series (title) VALUES ("Ice and Fire");
INSERT INTO series (title) VALUES ("HBO");
INSERT INTO books (title, series_id) VALUES ("Ice", 1);
INSERT INTO books (title, series_id) VALUES ("Fire", 1);
INSERT INTO books (title, series_id) VALUES ("Wind", 1);
INSERT INTO books (title, series_id) VALUES ("HBO1", 2);
INSERT INTO books (title, series_id) VALUES ("HBO2", 2);
INSERT INTO books (title, series_id) VALUES ("HBO3", 2);
INSERT INTO characters (name, series_id) VALUES ("Jon Snow", 1);
INSERT INTO characters (name, series_id) VALUES ("Khaleesi", 1);
INSERT INTO characters (name, series_id) VALUES ("Tyrion", 1);
INSERT INTO characters (name, series_id) VALUES ("Jaime", 1);
INSERT INTO characters (name, series_id) VALUES ("Taco", 2);
INSERT INTO characters (name, series_id) VALUES ("Nacho", 2);
INSERT INTO characters (name, series_id) VALUES ("Paco", 2);
INSERT INTO characters (name, series_id) VALUES ("Avocado", 2);
INSERT INTO subgenres (name) VALUES (null);
INSERT INTO subgenres (name) VALUES (null);
INSERT INTO authors (name) VALUES ("George");
INSERT INTO authors (name) VALUES ("HBO Producer");
INSERT INTO character_books (book_id, character_id) VALUES (1, 1);
INSERT INTO character_books (book_id, character_id) VALUES (2, 1);
INSERT INTO character_books (book_id, character_id) VALUES (3, 1);
INSERT INTO character_books (book_id, character_id) VALUES (1, 2);
INSERT INTO character_books (book_id, character_id) VALUES (2, 2);
INSERT INTO character_books (book_id, character_id) VALUES (3, 2);
INSERT INTO character_books (book_id, character_id) VALUES (3, 3);
INSERT INTO character_books (book_id, character_id) VALUES (1, 4);
INSERT INTO character_books (book_id, character_id) VALUES (4, 5);
INSERT INTO character_books (book_id, character_id) VALUES (5, 5);
INSERT INTO character_books (book_id, character_id) VALUES (6, 5);
INSERT INTO character_books (book_id, character_id) VALUES (4, 6);
INSERT INTO character_books (book_id, character_id) VALUES (5, 6);
INSERT INTO character_books (book_id, character_id) VALUES (6, 6);
INSERT INTO character_books (book_id, character_id) VALUES (6, 7);
INSERT INTO character_books (book_id, character_id) VALUES (4, 8);
